config/routes.rb
Search::Application.routes.draw do
  resources :webs,:containers
  match '/newword' =>'webcontainers#new'

  root :to => 'webs#new'

end

app/models/container.rb
class Container < ActiveRecord::Base
  has_many :webcontainers
  attr_accessible :description, :title, :url
end

app/models/web.rb
class Web < ActiveRecord::Base
   has_many :webcontainers	
  attr_accessible :word, :status
end

app/models/webcontainer.rb
require 'nokogiri'
class Webcontainer < ActiveRecord::Base
  belongs_to :web
  belongs_to :container
  attr_accessible :occu, :weight 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController
	def index
		@contain=Container.all
		
	end
end

app/controllers/webcontainers_controller.rb
class WebcontainersController < ApplicationController
	def new
		 @word=Rails.cache.read("word")
		 @word_id=Rails.cache.read("word_id")
		 @containers=Container.all
		 
		 @containers.each do |p|
		 	obj=Webcontainer.new
		 	obj.add("/home/sourcebits/search/public/search.html",@word,@word_id)
		 	#obj.save
		 end
	end
end

app/controllers/webs_controller.rb
class WebsController < ApplicationController
  # GET /webs
  # GET /webs.json
  def index
      @web = Web.new
  end


  # GET /webs/1
  # GET /webs/1.json
  def show
    @web = Web.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @web }
    end
  end

  # GET /webs/new
  # GET /webs/new.json
  def new
    @web= Web.new
  end

  # GET /webs/1/edit
  def edit
    @web = Web.find(params[:id])
  end
  def mymethod
    @web= Web.new
  end
  # POST /webs
  # POST /webs.json
  def create
    
    #@word= params[:web][:word]
    @result=[]
    word=params[:web][:word]
    word=word.split(' ')
    i=0
    word.each do |x|
      #p x
      @web=Web.find_by_sql("select id from webs where word= '#{x}'")
      #@web=Web.where("word=?",params[:web][:word])
      #@result= Container.joins('INNER JOIN WebContainer on Container.id=Webcontainer.container_id')
      #@result= Container.webcontainer.find_by_word_id(17);
      st=Container.all(:joins => :webcontainers,:conditions => {:webcontainers => {:web_id => @web}}, :order => "webcontainers.weight desc")
      int=st&@result
      difa=@result-st
      difb=st-@result
      @result=int+difa+difb 
    end
    cr=0
    @newresult=[]
    @result.each do |y|
      y=y.title
      y=y.split(' ')
      i=0
      word.each do |z|
        if(y[i].match(/^#{z}$/i)!=nil)
          i=i+1
        else
          break
        end
      end
      if(i==word.count)
        @newresult.push(@result[cr])
      end
      cr=cr+1
    end
    tempar=@result-@newresult
    @newresult=@newresult+tempar
    @result=@newresult
    @web=Web.new
    @showw=params[:web][:word]
    puts @showw
    puts @showw.class
  end

  # PUT /webs/1
  # PUT /webs/1.json
  def update
    @web = Web.find(params[:id])

    respond_to do |format|
      if @web.update_attributes(params[:web])
        format.html { redirect_to @web, notice: 'Web was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @web.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /webs/1
  # DELETE /webs/1.json
  def destroy
    @web = Web.find(params[:id])
    @web.destroy

    respond_to do |format|
      format.html { redirect_to webs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/helpers/webcontainers_helper.rb
module WebcontainersHelper
end

app/helpers/webs_helper.rb
module WebsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Search</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/webcontainers/new.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @containers.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.description %></td>
    <td><%= post.url %></td>
   </tr>
<% end %>
</table>

app/views/webs/_form.html.erb
<%= stylesheet_link_tag 'mycss.css' %>
<%= form_for(@web) do |f| %>
  

  <div class="field">
    <%= f.label :word %><br />
    <div class= "text_field_effect" >
    <%= f.text_field :word  %>
	</div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/webs/create.html.erb
<div>
	<span id="searchagain">
		<span id="simage" float="left">
			<h1>Mr. Holmes</h1>
		</span>
		<span id="ssearch" float="left">
			<div>
				<h2>Search again</h2>
			</div>
			<div>
			<form action="/webs" method="post">
			
				<input type="textfield" name="web[word]" value= "<%= @showw %>" size="60" onfocus="this.value='' "/>
				<input type="submit" value="search" />
			</form>
			</div>
		</span>

	</span>

	<% if @result.count>0 %>
	<div id="tota">
		<div id="lefts" >
			Results
		</div>
		<div id="rights" >
			
			<% @result.each do |post| %>
			<a href="<%= post.url%>">
			<div id="title">
				<%= post.title%>
			</div>
			<div id="url">
				<%= post.url %>
			</div>
			<div id="description">
				<%= post.description %>
			</div><br/>
			

			<%end%>
			</a>
		</div>
	</div>
	<%else%>
	<div id="tota">
		<div id="lefts" >
			Results
		</div>
		<div id="rights" >
		<h2><i>No match till now</i></h2>
		</div>
	</div>
	<%end%>
</div>

app/views/webs/edit.html.erb
<h1>Editing web</h1>

<%= render 'form' %>

<%= link_to 'Show', @web %> |
<%= link_to 'Back', webs_path %>

app/views/webs/index.html.erb
<h1>sourcebits website</h1>
<%= render 'form' %>

app/views/webs/mymethod.html.erb
hi

app/views/webs/new.html.erb
<%= stylesheet_link_tag 'word.css'%>

	<div id="total">
		<div id="image">
			<h1>Mr. Holmes</h1>
		</div>
		<div id="search">
			<form action="/webs" method="post">
			
				<input type="textfield" name="web[word]" value="Ask Mr. Holmes"  size="60" onfocus="this.value='' "/>
				<input type="submit" value="search" />
			</form>
		</div>
		<div id="source" >
			<p align="right">
				Powered by Sourcebits
			</p>
				
		</div>
	</div>

app/views/webs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Word:</b>
  <%= @web.word %>
</p>


<%= link_to 'Edit', edit_web_path(@web) %> |
<%= link_to 'Back', webs_path %>